name: CI
on:
  push:
    tags:
      - testing-*

jobs:
  build_ios:
    name: Build Flutter (iOS)
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
    - name: Get tag
      id: get-tag
      uses: dawidd6/action-get-tag@v1
    - uses: jungwinter/split@v1
      id: split
      with:
        msg: ${{steps.get-tag.outputs.tag}}
        seperator: "-"
    - name: just echo a message
      run: |
        echo ${{ steps.split.outputs._2 }}
#     - name: Setup iOS Certs
#       uses: Apple-Actions/import-codesign-certs@v1
#       with:
#         p12-file-base64: ${{ secrets.CERTIFICATES_FILE_BASE64 }}
#         p12-password: ${{ secrets.CERTIFICATES_PASSWORD }}
#     - name: Create Provision Profiles directory
#       run: |
#         mkdir -p "/Users/runner/Library/MobileDevice/Provisioning Profiles"
#     - name: Setup Provision Profile
#       uses: RollyPeres/base64-to-path@v1
#       with:
#         filePath: /Users/runner/Library/MobileDevice/Provisioning Profiles/86ce4d81-fd7e-46b2-ae6a-3092b4af6cd7.mobileprovision
#         encodedString: ${{ secrets.PROVISIONING_PROFILE }}
#     - name: Bundle install
#       run: cd ./ios && bundle install
#     - uses: actions/setup-java@v1
#       with:
#         java-version: '12.x'
#     - uses: subosito/flutter-action@v1
#       with:
#           channel: 'stable'
#     - name: Install tools
#       run: |
#         flutter pub get
#         cd ./ios && pod install
#     - name: Deploy to TestFlight
#       run: |
#         cd ./ios && bundle exec fastlane archive
    # - run: flutter pub get
    # - name: Install Dependencies
    #   run: |
    #     cd ios
    #     pod install
    #   shell: bash
    # - run: flutter build ipa --release --export-options-plist=ExportOptions.plist
#     - name: Upload XCArchive
#       uses: actions/upload-artifact@v1
#       with:
#         name: Runner.xcarchive
#         path: ios/fastlane/archives
    # - name: Prepare IPA
    #   run: |
    #     mv build/ios/ipa/calclist.ipa build/ios/ipa/WMG_AMP_Enterprise.ipa
    # - uses: shallwefootball/s3-upload-action@master
    #   with:
    #     aws_key_id: ${{ secrets.AWS_KEY_ID }}
    #     aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
    #     aws_bucket: wmg-amp-mobile-api-staging
    #     source_dir: build/ios/ipa
    #     destination_dir: builds/v4-10/
